
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: federation-app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/karectl/kare-federation.git
    targetRevision: main
    path: appsets
    kustomize:
      commonLabels:
        app.kubernetes.io/managed-by: argocd
      commonAnnotations:
        app.kubernetes.io/part-of: karectl
      patches:
        - target:
            kind: ApplicationSet
          patch: |-
            - op: replace
              path: /spec/generators/0/matrix/generators/0/git/repoURL
              value: https://github.com/karectl/kare-federation.git
            - op: replace
              path: /spec/generators/0/matrix/generators/0/git/revision
              value: main
        - target:
            kind: ApplicationSet
            labelSelector: "karectl.io/source-type=multiple"
          patch: |-
            - op: replace
              path: /spec/template/spec/sources/1/repoURL
              value: https://github.com/karectl/kare-federation.git
            - op: replace
              path: /spec/template/spec/sources/1/targetRevision
              value: main
        - target:
            kind: ApplicationSet
            labelSelector: "karectl.io/source-type!=multiple"
          patch: |-
            - op: replace
              path: /spec/template/spec/source/repoURL
              value: https://github.com/karectl/kare-federation.git
            - op: replace
              path: /spec/template/spec/source/targetRevision
              value: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  info:
    - name: KARE-Federation App of Apps
      value: "https://github.com/karectl/kare-federation"
    - name: KARE-Federation Documentation
      value: "https://karectl.github.io/kare-federation/"